GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/create
Content-Type: application/json

{
  "text": "Order Huge Pizza"
}

###

DELETE http://localhost:3001/todo/delete/659b8f5ee64438ebea41de54

###

PUT http://localhost:3001/todo/complete/659b91e175d0c88bc2a40e61